#!/usr/bin/env python3
"""Immutable YOLO baseline for comparison.

Do not edit this file during the booth flow. Participants edit challenge.py.
"""

from __future__ import annotations


def run() -> dict:
    return {
        "cost": 3.82,
        "quality": 92,
        "speed": 18.0,
        "tokens": 220,
        "workflow": "Travel Planner",
        "prompt": "original YOLO baseline: premium model for every step",
        "plan": "Premium model searched, summarized, ranked, and formatted in one pass.",
        "trace": [
            {
                "step": "YOLO all-in-one",
                "capability": "premium model everywhere",
                "impact": "search + summarize + rank + format all paid as premium reasoning",
                "tokens": 220_000,
                "cost": 3.82,
                "seconds": 18.0,
            }
        ],
    }


if __name__ == "__main__":
    result = run()
    print(f"cost=${result['cost']} quality={result['quality']} time={result['speed']}s tokens={result['tokens']}k")
